embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"bg_2\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 25.0\n"
  "  y: 5.0\n"
  "  z: 25.0\n"
  "  w: 5.0\n"
  "}\n"
  "size {\n"
  "  x: 700.0\n"
  "  y: 9999.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/main.atlas\"\n"
  "}\n"
  ""
}
